### ISSUE TITLE
Assumption of lattice vectors

### ISSUE THREAD

**Issue by atbug** [QijingZheng/VaspBandUnfolding#11]
I was trying to parse WAVECAR myself and was trying to read both your program and Feenstra's program (http://www.andrew.cmu.edu/user/feenstra/wavetrans/source/WaveTrans.f90). It seems the following code assumes the lattice vectors are orthogonal:
https://github.com/QijingZheng/VaspBandUnfolding/blob/8cd0a45a531bbafb1ab095df2ab387e65c590d3a/vaspwfc.py#L178-L180

If the reciprocal lattice vectors are `b1=[-0.99, 0.01, 0.0]`, `b2=[0.99, 0.01, 0.0]`, `b3=[0, 0, 1.0]` and the wave vector corresponding to the energy cutoff is `G=10`, the norm of `n*b1+n*b2` is smaller than `G` as long as `n<500`. But the above code would estimate `n<=100`.

**Comment by QijingZheng** [comment]
Hi

In my code, there is no such assumption that the lattice should be orthogonal. In fact, the snippet you showed is just a rewrite of the Fortran code of VASP. Please refer to the VASP source code, e.g. vasp.5.4.4 main.F ln966-968. Moreover, the number of g-vectors generated by my code and VASP are consistent, otherwise there will be a error and the code will not proceed. 

In your example, your estimation is correct about n <= 500. However, please note that Anorm is the norm of the real-space basis vectors other than the reciprocal-space ones.

Since you mentioned WaveTrans.f90, I have to tell you that the code calculates the real-space wavefunction in a stupid way, i.e. the author just added all the plane-waves one by one which is inefficient and takes a long time. On the other hand, the more efficient way is use the FFT to do the transformation. I have seen someone used the wavetrans.f90 algorithm to plot the wavefunction and it took about 1 hour to get just one KS orbital, while my code get the same orbital in just 1 second.

```
!!$*   Calculate plane waves
      ncnt=0
      do ig3=0,2*nb3max
         ig3p=ig3
         if (ig3.gt.nb3max) ig3p=ig3-2*nb3max-1
         do ig2=0,2*nb2max
            ig2p=ig2
            if (ig2.gt.nb2max) ig2p=ig2-2*nb2max-1
            do ig1=0,2*nb1max
               ig1p=ig1
               if (ig1.gt.nb1max) ig1p=ig1-2*nb1max-1
               do j=1,3
                  sumkg(j)=(wk(1)+ig1p)*b1(j)+ &
                       (wk(2)+ig2p)*b2(j)+(wk(3)+ig3p)*b3(j)
               enddo
               gtot=sqrt(sumkg(1)**2+sumkg(2)**2+sumkg(3)**2)
               etot=gtot**2/c
               if (etot.lt.ecut) then
                  ncnt=ncnt+1
                  igall(1,ncnt)=ig1p
                  igall(2,ncnt)=ig2p
                  igall(3,ncnt)=ig3p
               end if
            enddo
         enddo
```

**Comment by atbug** [comment]
Thank you.

I am trying to port the code to julia. I now realize your code is indeed correct. Sorry for the interuption.
